ServerEvents.recipes(event => {
    event.remove({ output: 'simplyjetpacks:jetpack_vanilla1' })
    event.remove({ output: 'simplyjetpacks:jetpack_vanilla2' })
    event.remove({ output: 'simplyjetpacks:jetpack_vanilla3' })
    event.remove({ output: 'simplyjetpacks:jetpack_vanilla4' })
    event.remove({ output: 'simplyjetpacks:thruster_vanilla1' })
    event.remove({ output: 'simplyjetpacks:thruster_vanilla2' })
    event.remove({ output: 'simplyjetpacks:thruster_vanilla3' })
    event.remove({ output: 'simplyjetpacks:thruster_vanilla4' })

    event.remove({ output: 'simplyjetpacks:jetpack_mek1' })
    event.remove({ output: 'simplyjetpacks:jetpack_mek2' })
    event.remove({ output: 'simplyjetpacks:jetpack_mek3' })
    event.remove({ output: 'simplyjetpacks:jetpack_mek4' })
    event.remove({ output: 'simplyjetpacks:thruster_mek1' })
    event.remove({ output: 'simplyjetpacks:thruster_mek2' })
    event.remove({ output: 'simplyjetpacks:thruster_mek3' })
    event.remove({ output: 'simplyjetpacks:thruster_mek4' })
})