JEIEvents.hideItems(event => {
    event.hide('simplyjetpacks:jetpack_vanilla1')
    event.hide('simplyjetpacks:jetpack_vanilla2')
    event.hide('simplyjetpacks:jetpack_vanilla3')
    event.hide('simplyjetpacks:jetpack_vanilla4')
    event.hide('simplyjetpacks:jetpack_vanilla1_armored')
    event.hide('simplyjetpacks:jetpack_vanilla2_armored')
    event.hide('simplyjetpacks:jetpack_vanilla3_armored')
    event.hide('simplyjetpacks:jetpack_vanilla4_armored')
    event.hide('simplyjetpacks:thruster_vanilla1')
    event.hide('simplyjetpacks:thruster_vanilla2')
    event.hide('simplyjetpacks:thruster_vanilla3')
    event.hide('simplyjetpacks:thruster_vanilla4')

    event.hide('simplyjetpacks:jetpack_mek1')
    event.hide('simplyjetpacks:jetpack_mek2')
    event.hide('simplyjetpacks:jetpack_mek3')
    event.hide('simplyjetpacks:jetpack_mek4')
    event.hide('simplyjetpacks:jetpack_mek1_armored')
    event.hide('simplyjetpacks:jetpack_mek2_armored')
    event.hide('simplyjetpacks:jetpack_mek3_armored')
    event.hide('simplyjetpacks:jetpack_mek4_armored')
    event.hide('simplyjetpacks:thruster_mek1')
    event.hide('simplyjetpacks:thruster_mek2')
    event.hide('simplyjetpacks:thruster_mek3')
    event.hide('simplyjetpacks:thruster_mek4')
})